pfitzpaddy/ngm-reportEngine

- api/controllers/ReportHub/UserController.js
Congratulations on user profile, very nice,  take a look at using promises for updating collections
> Using promises in place of callbackes

- api/controllers/Cluster/ProjectController.js
updates setProjectById to update project and report related collections with user data
related to [reportHub pull request](https://github.com/pfitzpaddy/ngm-reportHub/pull/17)
> feature: contact details update

- api/controllers/Cluster/Reports/ReportController.js
- api/controllers/Cluster/Stocks/StockReportController.js
- api/models/Cluster/Stocks/Stock.js
root branch 
1. return in addition to stock report locations
2. on download month stock csv exclude location_id with null.
3. add to stock model stock_item_purpose.
> Enhance stock reporting

- api/controllers/Cluster/Stocks/StockReportController.js
- api/models/Cluster/Stocks/StockLocation.js
- api/models/Cluster/Stocks/StockWarehouse.js
branch of https://github.com/pfitzpaddy/ngm-reportEngine/pull/15
1. adds month date marker for warehouse deleting, get report 
2. dynamic warehouse date range report generation
> Ammend on del warehouses

- api/controllers/Cluster/Stocks/StockReportController.js
branch of https://github.com/pfitzpaddy/ngm-reportEngine/pull/15
1. get stock report previous report api
> Feature cp prev report

- api/controllers/Cluster/ProjectController.js
- config/routes.js
api, can also replace getProjectById
> feature: project export

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
- api/controllers/Cluster/Reports/ReportController.js
1. no fields if no report will return error in some cases,
2. null location_id fixed in enhance-stock-reporting branch
> fix: stock csv export if null location_id

- api/controllers/Cluster/Dashboards/AdminDashboardController.js
- api/controllers/Cluster/ProjectController.js
- config/routes.js
adds export from project finance and admin dash
> feature: project/s csv financial export

- api/controllers/Cluster/Reports/ReportTasksController.js
- api/models/Cluster/Project/TargetLocation.js
the same processing technique as per locations but with reports, as it has project focal point user fields, and adding if user not found in project locations.
additionally fixing bug when on a new project creation if setting locations with other then focal point user, it would save target locations with the focal point.
> Enhance/issue 25/notification focal point

- .gitignore
- api/controllers/Country/Afg/Nutrition/NutritionController.js
- api/controllers/Country/Afg/Nutrition/NutritionDashboardController.js
- api/models/Nutrition/NutritionBeneficiaries.js
- api/models/Nutrition/NutritionReports.js
- config/policies.js
- config/routes.js
- tasks/db/ngm_nutrition_getKoboData.sh
> new: afghanistan nutrition weekly

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
considerably improve processing speed, using native mongodb aggregation queries
> enhancement: cluster dashboard speedup

- api/controllers/Country/Afg/Drought/DroughtDashboardController.js
- config/routes.js
add-drought-dashboard
add filter cluster
add-drought-dashboard
change beneficiary_type_name to beneficiary_type_id
add-drought-dashboard
add-drought-dashboard
add status, status_icon for report
add-drought-dashboard
add-drought-dashboard
> feature-drought-dashboard

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
> add-active-locations

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
add-pie-chart for children, adult and elderly
> add-pie-chart

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
Change API chart
change to native
Change API chart
cleaning
> change API chart into native queries

- api/models/Cluster/Stocks/Stock.js
Add stock report targeted groups selection
> Add stock targeted Group

- api/controllers/Cluster/Reports/ReportController.js
- api/models/Cluster/Report/Beneficiaries.js
- api/models/Cluster/Report/Location.js
it reduces time to save monthly report by using bulk update on locations and beneficiaries
note: on update locations only report_status updated, so that updated to bulk on it, insert new location and other updates are done on add/update target_location stage
tests: done
todo tests: different scenarios on servers on immap projects
todo dev: training locations bulk udpates
> update: set report with bulk update

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
> fix: incorect-rendering chart

- api/controllers/Cluster/Dashboards/AdminDashboardController.js
improves speed load of _due_ and _completed_ reports, by using native queries and reducing n of db request
tests: returns same json number of rows
> update: decrease admin reports load speed

- api/controllers/Cluster/Reports/ReportController.js
- api/models/Cluster/Report/Beneficiaries.js
+1ms on each beneficiary
removing also lodash import on Beneficiaries, so that using global sails one, as deepClone is not working
> fix: save beneficiaries without associations

- api/models/Cluster/Project/TargetBeneficiaries.js
- api/models/Cluster/Report/Beneficiaries.js
> update: cash reporting

- .gitignore
- api/controllers/ReportHub/FileController.js
- api/controllers/ReportHub/UserController.js
- api/models/Cluster/Documents/Documents.js
- config/routes.js
Reqires install: npm install googleapis --save
NOTES: es6 syntax used ( x => x...), should work in prod with updated node, but better to check
apis to upload to gdrive
on RH db only file metadata stored, fileid is dgrive file id
downloads, preview, thumbnails by direct gdrive link on FE
config/documents.js contains settings
service account set on rh email account
dgrive folders
RH_PROJECT_DOCUMENTS
RH_PROJECT_DOCUMENTS_DELETED
TODO: test for errors
TODO: to finish zip download api
TODO: document
> feature: gdrive documents apis

- api/controllers/ReportHub/FileController.js
Requires install 
**npm install node-fetch --save**
fn to return link for zip archive of specified files on gdrive
todo: update ngm-dashboard-framework to include zip download
> feature: gdrive zip download link

- api/models/ReportHub/UserHistory.js
remove afterCreate function on UserHistory with send email functionality
> bugfix: dont't send email second time on user creation

- api/controllers/ReportHub/FileController.js
- config/routes.js
Separate params, filter, zip functions.
Fix date params.
> Refactor upload functions

- api/controllers/ReportHub/FileController.js
Change project_id to report_id
> fix(upload): correct required param

- api/controllers/Cluster/Reports/ReportTasksController.js
- api/models/Cluster/Stocks/StockReport.js
- config/routes.js
- tasks/db/ngm_ctc_getKoboData.sh
- tasks/db/ngm_epr_getKoboData.sh
- tasks/db/ngm_nutrition_getKoboData.sh
- tasks/reports/ngm_reporthub_reports_open.sh
- tasks/reports/ngm_reporthub_reports_reminder.sh
- tasks/reports/ngm_reporthub_reports_todo.sh
- tasks/reports/ngm_reporthub_stocks_todo.sh
Fixes for stock reports generation.
Use Https in cron sh scripts.
> Fix reports generation

- api/controllers/Cluster/Reports/ReportController.js
- api/controllers/Cluster/Reports/ReportTasksController.js
Don't send notifications to location focal point.
Save report status on locations if changed.
> Only to project focal point reminders / set report status on locations

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
Add updatedAt, createdAt fields to beneficiaries csv download
Refactor formatting to async ( no considerable speed improvement on local )
> Beneficiaries download fields

- api/models/Cluster/Project/Project.js
- In Project.js model:
Added array fields for the 4 Project Classifications groups :  ‘undaf_desarrollo_paz’, ’acuerdos_de_paz’,’dac_oecd_development_assistance_committee’,’ods_objetivos_de_desarrollo_sostenible’
> Colombia Project Classifications

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
like cluster_ids[]=fsac&cluster_ids[]=esnfi in query parameters
> feat: add filter by array of clusters

- api/controllers/Cluster/ProjectController.js
In ProjectController.js in functionallity download project, added columns for each Project Classifications group: 'Undaf Desarrollo Paz','Acuerdos de Paz','DAC - OECD Development Assistance Committee', 'ODS - Objetivos de Desarrollo Sostenible'.
> Added Project Classifications columns to Project Download

- api/controllers/ReportHub/OrganizationController.js
- api/controllers/ReportHub/UserController.js
- api/models/ReportHub/UserLoginHistory.js
- config/routes.js
Requirements: record user logins to the system to produce stats
- record on login into UserLoginHistory
- api to get data from UserLoginHistory
> Record user logins

- api/controllers/Cluster/Reports/ReportController.js
- api/controllers/ReportHub/UserController.js
- api/models/Cluster/Report/Beneficiaries.js
- remove createdAt/updatedAt before beneficiary save so that Sails handles it itself ( correct save/update date for beneficiaries records )
- use of eachOf that has indexes to place beneficiaries in the same order
- ( optional ) add _order into Beneficiary model to easily keep track of order in location form ( + faster sort on fe )
> Fixes: resolve monthly report edit save lost beneficiaries order

- api/models/Cluster/Project/BudgetProgress.js
Added admin1 and admin2 columns to BudgetProgress model, to select Departamento and Municipio in COL Financial Report
> Fixes in BudgetProgress Model for COL

- api/controllers/ReportHub/UserController.js
1. pass empty updatedRelationsUser if organization or country change
2. add handle logic if organization change ( the same as for country )
> update(profile): handle on organization change

- api/models/Cluster/Project/Project.js
Model Project columns added:
Componentes de respuesta:
humanitarian_component
construccion_de_paz_component
desarrollo_sostenible_component
flujos_migratorios_component
plan project :
hrp_plan
rmrp_plan
interagencial_plan
budget by donor
gender marker
> Project changes

- api/controllers/Cluster/Reports/ReportTasksController.js
- config/routes.js
- views/email/notification-due-reports/html.ejs
- reminder send to only this reporting period month
- already using only project reports focal point
old function as setReportsReminderAllMonths can be used if sending notifications for all pending months ( for example in the end of reporting year to close all todo reports )
> update(notifications): send reminder for this month only

- api/controllers/Cluster/ProjectController.js
- api/controllers/Cluster/Reports/ReportController.js
- config/routes.js
Adds: 
- deleting reports outside project date range without beneficiaries on project save
- delete report api
also some linting empty space updates
> Project save: delete out of date range reports

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
> update(download): add fatp same province field for af

- api/controllers/ReportHub/FileController.js
tested on dev, not updated on dev
> fix(print): add running as root support

- api/controllers/ReportHub/FileController.js
for some reason on prod extended setObject not working
> fix(print): set storage with setItem

- api/controllers/Cluster/ProjectController.js
Needed for setting location reporter, project_copy was overwriting target location user.
> fix(locations): set user meta on project save

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
> update(dashboard cluster): change format subLabel in the center of highchart (donut/chart)

- api/controllers/Cluster/Dashboards/Cluster4wplusDashboardController.js
- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
- api/controllers/Cluster/ProjectController.js
added donor filter to downloads (projects, beneficiaries report, financial reports).
> added donor filter to downloads

- api/controllers/Cluster/Reports/ReportTasksController.js
new month report with actual createdAt
> update: generate new month report with actual createdAt not of project

- api/controllers/Cluster/ProjectController.js
- query project date by overlap with request query date range
```
start project-----------------------end project
start range----------------------------------end range 
```
- query multicluster projects
- add beneficiary, target beneficiaries, main cluster totals
- add project url
> Update projects download

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
cluster query on mpc purpose looks only for mpc cluster activities
note: mpc purpose is going to be updated for next year
&space removal
> update(filter): query mpc purpose if only mpc activity

- api/controllers/Cluster/Dashboards/Cluster4wplusDashboardController.js
- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
Fixes in Projects and Activities 4wPlus Dashboards.
It is necessary to execute the following command in Mongodb: 
db.getCollection ('targetbeneficiaries'). Remove ({'admin0pcode': 'COL', 'project_id': null})
With this command, the records of Target Beneficiaries that do not match Project are deleted.
The file activities.csv has been updated. It is requested to update the Activities in PROD.
> Entregable4 4wplus updated

- api/controllers/Cluster/Dashboards/Cluster4wplusDashboardController.js
- api/controllers/Cluster/Dashboards/Cluster4wprojectplanDashboardController.js
- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
- api/services/AreaCentroidService.js
- api/services/FilterObjectService.js
dynamic 5w marker coordinates based on admins on no project data
> update(markers): dynamic no data coordinates.

- api/controllers/Cluster/Dashboards/Cluster4wplusDashboardController.js
- api/controllers/Cluster/Dashboards/Cluster4wprojectplanDashboardController.js
fixes to show data in graphics
> fixes in project and activities dashboards

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
- api/models/Cluster/Report/Report.js
add programme_partners to download
fix report model programme_partners attribute
> Programme partner updates

- api/controllers/Cluster/Dashboards/AdminDashboardController.js
update(partners): add programme partners filtering
> update(partners): add programme partners filtering

- api/controllers/Cluster/Reports/ReportTasksController.js
- api/controllers/Cluster/Stocks/StockReportController.js
- api/controllers/ReportHub/OrganizationController.js
- api/models/Cluster/Stocks/Stock.js
- api/models/Cluster/Stocks/StockLocation.js
- api/models/Cluster/Stocks/StockReport.js
- api/models/Cluster/Stocks/StockWarehouse.js
- api/models/ReportHub/Organization.js
- api/services/Utils.js
- config/routes.js
+additional db updates, see comment for details
````
// remove report, locations for monthes after March
db.getCollection("stockreport").remove({report_year: 2020, report_month: {$gte: 3}});
db.getCollection("stocklocation").remove({report_year: 2020, report_month: {$gte: 3}});
// clean up unlinked hanging records
db.getCollection("stockwarehouse").remove({"organization_id" : null})
db.getCollection("stocklocation").remove({"report_id" : null});
db.getCollection("stock").remove({"location_id" : null});
// update stockwarehouse organization_id reference from ObjectId to String
db.getCollection("stockwarehouse").find({"organization_id" : {$ne: null}}).forEach(function(d){
print(d.organization_id.valueOf());
d.organization_id = d.organization_id.valueOf(); …
```
> update(stocks): migrate sails associations to async processing

- api/controllers/Cluster/ProjectController.js
Fix target locations query
Refactor queries
Add removeDuplicates to SetKey
Use eachOf
Add addProjectData fn action to get project derivative data
Return NO PROJECTS on no data
> fix(download): refactor project summaries

- api/controllers/Cluster/Reports/ReportController.js
> update(download:report): use mpc delivery name field

- api/controllers/Cluster/Reports/ReportController.js
- api/services/Utils.js
- config/policies.js
- config/routes.js
init download project lists as xlsx
> feature(api): add project lists xlsx download

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
- api/controllers/Cluster/Reports/ReportController.js
- api/models/Cluster/Stocks/Stock.js
- api/services/Utils.js
- add attributes (stock_type_id, stock_type_name, donors array, implementing_partners array, stock_details array, remarks
- update accordingly csv downloads
> Update stocks model ET

- api/models/Cluster/Project/Project.js
- api/models/Cluster/Report/Beneficiaries.js
- api/models/Cluster/Report/Report.js
// db update project_details
db.getCollection("project").find(
{ 
"admin0pcode" : "AF", 
//        "project_acbar_partner" : true
}
).forEach(function(d) {
if (d.project_acbar_partner) {
d.project_details = [{ project_detail_id: 'acbar_partner', project_detail_name: 'ACBAR Partner', project_detail_checked: true }];
} else {
d.project_details = [];
}
db.getCollection("project").save(d);
});
> update: covid19 reporting report

- api/controllers/ReportHub/OrganizationController.js
- api/models/Cluster/Stocks/StockWarehouse.js
warehouses can be updated
warehouses param in getOrganization request
> update(stocks): enable warehouses update

- api/controllers/ReportHub/ListController.js
- api/controllers/ReportHub/UserController.js
- api/models/ReportHub/Organizations.js
- api/policies/isAdmin.js
- api/services/jwtToken.js
- config/policies.js
- config/routes.js
for upcoming organizations list ui 
- set one organization
- get organizations csv
- delete one organization
- reset all organizations api
- set organizations strict schema
- add organizations admin0pcode_inactive attribute
- get timed jwt access token
- add gwt user role claim
- add isAdmin policy
> update api organizations list

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
> feat(api): get json beneficiaries or stocks by filter

- api/controllers/Cluster/Dashboards/ClusterDashboardController.js
- api/controllers/Cluster/ProjectController.js
- api/controllers/Cluster/Stocks/StockReportController.js
- api/models/Cluster/Stocks/Stock.js
- api/models/Cluster/Stocks/StockLocation.js
1. minor update project save error handing
2. add stock report status, report active
3. beneficiary download implementing and programme partners fields using abbreviations not the full name
> Update: project error handling/stock attributes/download ip,pp field values

- api/controllers/ReportHub/OrganizationController.js
- api/controllers/ReportHub/UserController.js
- api/models/ReportHub/Organization.js
- api/models/ReportHub/User.js
- config/routes.js
- views/email/cluster-new-user-pending/html.ejs
- views/email/cluster-new-user/html.ejs
- views/email/new-user-activated/html.ejs
- views/email/new-user-pending/html.ejs
- get registered organizations
- set registered organization
- add bool closed_registration attribute
- send email to organization admin/users for activation
- send email if a new organization to cluster, country admins
- rm menu organization cluster filter
- add loginhistory on reset
- notify on activation
> Update closed registration
